name: Generate Artifact

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Jalankan Proses Build
        run: |
          echo "Mulai build..."
          mkdir dist
          echo "<h1>Ini adalah hasil build otomatis Artifact</h1>" > dist/index.html
          echo "Build selesai"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-build-web
          path: dist/
          retention-days: 7
