name: CI Core Test

on:
  push:
    branches:
      - main

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Test Script
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: |
          echo "Pipeline Berjalan Sukses!"
          echo "Memeriksa secret key..."
          echo "Secret Key: $MY_SECRET_KEY"
